apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: ZooKeeper
  name: ocp-zookeeper
spec:
  tags:
  - annotations:
      description: Provides a ZooKeeper 3.3.0 distributed configuration server.
      openshift.io/display-name: ZooKeeper 3.3.0
      tags: zookeeper
      version: 3.3.0
    from:
      kind: DockerImage
      name: confluentinc/cp-zookeeper:3.3.0
    importPolicy: {}
    name: 3.3.0
  - annotations:
      description: Provides a ZooKeeper 3.3.x distributed configuration server.
      openshift.io/display-name: ZooKeeper (3.3.x)
      tags: zookeeper
      version: 3.3.x
    from:
      kind: ImageStreamTag
      name: 3.3.0
    importPolicy: {}
    name: 3.3.x
  - annotations:
      description: Provides a ZooKeeper distributed configuration server.
      openshift.io/display-name: ZooKeeper (Latest)
      tags: zookeeper
    from:
      kind: DockerImage
      name: confluentinc/cp-zookeeper:latest
    importPolicy: {}
    name: latest
